"""unmeasured recipe lines

Revision ID: 07b3e4937b81
Revises: 68612f2c694f
Create Date: 2026-08-21 08:08:51.952307
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "07b3e4937b81"
down_revision: str | None = "68612f2c694f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_line", schema=None) as batch_op:
        batch_op.alter_column(
            "magnitude", existing_type=sa.NUMERIC(precision=12, scale=4), nullable=True
        )
        batch_op.alter_column("unit", existing_type=sa.VARCHAR(length=20), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_line", schema=None) as batch_op:
        batch_op.alter_column("unit", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.alter_column(
            "magnitude", existing_type=sa.NUMERIC(precision=12, scale=4), nullable=False
        )

    # ### end Alembic commands ###
