"""pictures on an academy page

Revision ID: 1a99ba24932b
Revises: 7b9bd6550fa9
Create Date: 2026-08-26 21:02:34.391168
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "1a99ba24932b"
down_revision: str | None = "7b9bd6550fa9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academy_picture",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["academy_page.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("academy_picture", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_academy_picture_media_id"), ["media_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_academy_picture_page_id"), ["page_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("academy_picture", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_academy_picture_page_id"))
        batch_op.drop_index(batch_op.f("ix_academy_picture_media_id"))

    op.drop_table("academy_picture")
    # ### end Alembic commands ###
