"""nutrient profiles and piece weights

Revision ID: 26a476b10780
Revises: 3ee6ffe29742
Create Date: 2026-08-22 00:03:03.679684
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "26a476b10780"
down_revision: str | None = "3ee6ffe29742"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutrient_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("SWISS", "CIQUAL", "COFID", "USDA", name="nutritionsource"),
            nullable=False,
        ),
        sa.Column(
            "nutrient",
            sa.Enum(
                "ENERGY_KJ",
                "ENERGY_KCAL",
                "FAT",
                "SATURATES",
                "CARBOHYDRATE",
                "SUGARS",
                "FIBRE",
                "PROTEIN",
                "SALT",
                name="nutrient",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingredient_id", "source", "nutrient", name="uq_nutrient_profile"),
    )
    with op.batch_alter_table("nutrient_profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nutrient_profile_ingredient_id"), ["ingredient_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_nutrient_profile_source"), ["source"], unique=False)

    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("piece_grams", sa.Numeric(precision=8, scale=2), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.drop_column("piece_grams")

    with op.batch_alter_table("nutrient_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nutrient_profile_source"))
        batch_op.drop_index(batch_op.f("ix_nutrient_profile_ingredient_id"))

    op.drop_table("nutrient_profile")
    # ### end Alembic commands ###
