"""a meal that was cooked

Revision ID: 27a108b4bb88
Revises: 2e369d0eeb9a
Create Date: 2026-08-21 17:24:29.786413
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "27a108b4bb88"
down_revision: str | None = "2e369d0eeb9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plan_slot", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cooked_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plan_slot", schema=None) as batch_op:
        batch_op.drop_column("cooked_at")

    # ### end Alembic commands ###
