"""recipe serves

Revision ID: 2e369d0eeb9a
Revises: 74ed76ee047e
Create Date: 2026-08-21 13:17:23.788256
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2e369d0eeb9a"
down_revision: str | None = "74ed76ee047e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("serves", sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_column("serves")

    # ### end Alembic commands ###
