"""allergen classification

Revision ID: 3ec1242366a9
Revises: b4f60432b449
Create Date: 2026-08-20 22:38:10.302894
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3ec1242366a9"
down_revision: str | None = "b4f60432b449"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_allergen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column(
            "allergen",
            sa.Enum(
                "GLUTEN",
                "CRUSTACEANS",
                "EGGS",
                "FISH",
                "PEANUTS",
                "SOYBEANS",
                "MILK",
                "TREE_NUTS",
                "CELERY",
                "MUSTARD",
                "SESAME",
                "SULPHITES",
                "LUPIN",
                "MOLLUSCS",
                name="allergen",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingredient_id", "allergen", name="uq_ingredient_allergen"),
    )
    with op.batch_alter_table("ingredient_allergen", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingredient_allergen_ingredient_id"), ["ingredient_id"], unique=False
        )

    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("allergens_classified", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.drop_column("allergens_classified")

    with op.batch_alter_table("ingredient_allergen", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_allergen_ingredient_id"))

    op.drop_table("ingredient_allergen")
    # ### end Alembic commands ###
