"""cooking sessions and their timers

Revision ID: 3ee6ffe29742
Revises: 956712e51b34
Create Date: 2026-08-21 18:59:23.335156
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3ee6ffe29742"
down_revision: str | None = "956712e51b34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cooking_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column("plan_slot_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("at_step", sa.Integer(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "outcome", sa.Enum("COMPLETED", "ABANDONED", name="sessionoutcome"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_slot_id"],
            ["plan_slot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cooking_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cooking_session_cook_id"), ["cook_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cooking_session_plan_slot_id"), ["plan_slot_id"], unique=False
        )

    op.create_table(
        "cooking_timer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("step_position", sa.Integer(), nullable=False),
        sa.Column("running_since", sa.DateTime(), nullable=True),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["cooking_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "step_position", name="uq_cooking_timer"),
    )
    with op.batch_alter_table("cooking_timer", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cooking_timer_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cooking_timer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cooking_timer_session_id"))

    op.drop_table("cooking_timer")
    with op.batch_alter_table("cooking_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cooking_session_plan_slot_id"))
        batch_op.drop_index(batch_op.f("ix_cooking_session_cook_id"))

    op.drop_table("cooking_session")
    # ### end Alembic commands ###
