"""the academy

Three tables, shaped like the ingredient registry: a page, its text per language, and the
terms it answers to (ADR-057).

`academy_term` is deliberately **not** unique on (locale, normalised), which is where it
parts company with `ingredient_name`. Several pages may claim a term and the page names
the others at the top, because nothing computes on a page (ADR-058).


Revision ID: 5223cf09b215
Revises: ea6b9b7fea01
Create Date: 2026-08-26 16:14:42.480352
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "5223cf09b215"
down_revision: str | None = "ea6b9b7fea01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academy_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sa.Enum("TECHNIQUE", name="pagekind"), nullable=False),
        sa.Column("origin", sa.Enum("SEED", "USER", name="origin"), nullable=False),
        sa.Column("generated", sa.Boolean(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("academy_page", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_academy_page_approved"), ["approved"], unique=False)
        batch_op.create_index(batch_op.f("ix_academy_page_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_academy_page_slug"), ["slug"], unique=True)

    op.create_table(
        "academy_term",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("spelling", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("normalised", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["academy_page.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("page_id", "locale", "normalised", name="uq_academy_term"),
    )
    with op.batch_alter_table("academy_term", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_academy_term_locale"), ["locale"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_academy_term_normalised"), ["normalised"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_academy_term_page_id"), ["page_id"], unique=False)

    op.create_table(
        "academy_text",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("caution", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["academy_page.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("page_id", "locale", name="uq_academy_text"),
    )
    with op.batch_alter_table("academy_text", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_academy_text_locale"), ["locale"], unique=False)
        batch_op.create_index(batch_op.f("ix_academy_text_page_id"), ["page_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("academy_text", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_academy_text_page_id"))
        batch_op.drop_index(batch_op.f("ix_academy_text_locale"))

    op.drop_table("academy_text")
    with op.batch_alter_table("academy_term", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_academy_term_page_id"))
        batch_op.drop_index(batch_op.f("ix_academy_term_normalised"))
        batch_op.drop_index(batch_op.f("ix_academy_term_locale"))

    op.drop_table("academy_term")
    with op.batch_alter_table("academy_page", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_academy_page_slug"))
        batch_op.drop_index(batch_op.f("ix_academy_page_kind"))
        batch_op.drop_index(batch_op.f("ix_academy_page_approved"))

    op.drop_table("academy_page")
    # ### end Alembic commands ###
