"""accounts are applied for

Revision ID: 5925124b9ca7
Revises: 97d1228b8233
Create Date: 2026-08-22 19:47:19.339864
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5925124b9ca7"
down_revision: str | None = "97d1228b8233"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    standing = sa.Enum("APPLIED", "APPROVED", "REFUSED", name="standing")

    # Backfilled as APPROVED: every account that exists predates the application process
    # and its owner is already using this instance. Locking them out to record a decision
    # nobody was asked to make would be the migration deciding something it has no
    # standing to decide.
    with op.batch_alter_table("cook", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("standing", standing, nullable=False, server_default="APPROVED")
        )

    # The default goes once it has done its work. New accounts state their standing at the
    # call site (`CookAccess.register`), and a column default would quietly answer for a
    # code path that forgot to.
    with op.batch_alter_table("cook", schema=None) as batch_op:
        batch_op.alter_column("standing", existing_type=standing, server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cook", schema=None) as batch_op:
        batch_op.drop_column("standing")

    # ### end Alembic commands ###
