"""guided setup

Revision ID: 68612f2c694f
Revises: b0de70663ab7
Create Date: 2026-08-21 06:38:37.282849
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "68612f2c694f"
down_revision: str | None = "b0de70663ab7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setup_declaration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column(
            "step",
            sa.Enum("HOUSEHOLD", "CONSTRAINTS", "UNITS", "LOCALE", name="setupstep"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cook_id", "step", name="uq_setup_declaration"),
    )
    with op.batch_alter_table("setup_declaration", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_setup_declaration_cook_id"), ["cook_id"], unique=False)

    with op.batch_alter_table("cook", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cook", schema=None) as batch_op:
        batch_op.drop_column("locale")

    with op.batch_alter_table("setup_declaration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setup_declaration_cook_id"))

    op.drop_table("setup_declaration")
    # ### end Alembic commands ###
