"""plans and reservations

Revision ID: 74ed76ee047e
Revises: ce4b4d2452d9
Create Date: 2026-08-21 12:49:10.211256
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "74ed76ee047e"
down_revision: str | None = "ce4b4d2452d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meal_plan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_meal_plan_cook_id"), ["cook_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_meal_plan_starts_on"), ["starts_on"], unique=False)

    op.create_table(
        "plan_slot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column(
            "meal", sa.Enum("BREAKFAST", "LUNCH", "DINNER", "SNACK", name="meal"), nullable=False
        ),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["meal_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "on_date", "meal", name="uq_plan_slot"),
    )
    with op.batch_alter_table("plan_slot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_slot_on_date"), ["on_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_plan_slot_plan_id"), ["plan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_plan_slot_recipe_id"), ["recipe_id"], unique=False)

    op.create_table(
        "reservation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_item_id", sa.Integer(), nullable=False),
        sa.Column("plan_slot_id", sa.Integer(), nullable=False),
        sa.Column("magnitude", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_slot_id"],
            ["plan_slot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_item_id"],
            ["stock_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reservation_plan_slot_id"), ["plan_slot_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reservation_stock_item_id"), ["stock_item_id"], unique=False
        )

    op.create_table(
        "slot_attendee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("eater_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eater_id"],
            ["eater.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["plan_slot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slot_id", "eater_id", name="uq_slot_attendee"),
    )
    with op.batch_alter_table("slot_attendee", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_slot_attendee_eater_id"), ["eater_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_slot_attendee_slot_id"), ["slot_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slot_attendee", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_slot_attendee_slot_id"))
        batch_op.drop_index(batch_op.f("ix_slot_attendee_eater_id"))

    op.drop_table("slot_attendee")
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reservation_stock_item_id"))
        batch_op.drop_index(batch_op.f("ix_reservation_plan_slot_id"))

    op.drop_table("reservation")
    with op.batch_alter_table("plan_slot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_slot_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_plan_slot_plan_id"))
        batch_op.drop_index(batch_op.f("ix_plan_slot_on_date"))

    op.drop_table("plan_slot")
    with op.batch_alter_table("meal_plan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meal_plan_starts_on"))
        batch_op.drop_index(batch_op.f("ix_meal_plan_cook_id"))

    op.drop_table("meal_plan")
    # ### end Alembic commands ###
