"""step attention

How much of the cook each step asks for (ADR-037). Every existing step takes `HANDS_ON`,
which is both the default a new step gets and the reading that over-reports the work
rather than under-reporting it: a recipe already stored is described as more effort than
it is, never as less, and nobody is made late by the migration.

Revision ID: 956712e51b34
Revises: 27a108b4bb88
Create Date: 2026-08-21 18:16:54.061433
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "956712e51b34"
down_revision: str | None = "27a108b4bb88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("step", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "attention",
                sa.Enum("HANDS_ON", "WAITING", "AHEAD", name="attention"),
                nullable=False,
                server_default="HANDS_ON",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("step", schema=None) as batch_op:
        batch_op.drop_column("attention")

    # ### end Alembic commands ###
