"""shopping ticks

Revision ID: 97d1228b8233
Revises: bf9fe8c2c697
Create Date: 2026-08-22 11:35:30.680891
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "97d1228b8233"
down_revision: str | None = "bf9fe8c2c697"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_tick",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("magnitude", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column("ticked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["meal_plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "ingredient_id", name="uq_shopping_tick"),
    )
    with op.batch_alter_table("shopping_tick", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shopping_tick_ingredient_id"), ["ingredient_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_shopping_tick_plan_id"), ["plan_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shopping_tick", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shopping_tick_plan_id"))
        batch_op.drop_index(batch_op.f("ix_shopping_tick_ingredient_id"))

    op.drop_table("shopping_tick")
    # ### end Alembic commands ###
