"""recipes

Revision ID: abfaaf38d543
Revises: fc7553d6568e
Create Date: 2026-08-20 19:13:18.529370
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "abfaaf38d543"
down_revision: str | None = "fc7553d6568e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("yield_magnitude", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "yield_unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.Enum("AUTHORED", "IMPORTED_JSON", "IMPORTED_URL", "GENERATED", name="provenance"),
            nullable=False,
        ),
        sa.Column("visibility", sa.Enum("PRIVATE", "PUBLIC", name="visibility"), nullable=False),
        sa.Column("origin", sa.Enum("SEED", "USER", name="origin"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_cook_id"), ["cook_id"], unique=False)

    op.create_table(
        "ingredient_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("magnitude", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column("preparation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingredient_line", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingredient_line_ingredient_id"), ["ingredient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ingredient_line_recipe_id"), ["recipe_id"], unique=False
        )

    op.create_table(
        "step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("temperature_celsius", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("step", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_step_recipe_id"), ["recipe_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("step", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_step_recipe_id"))

    op.drop_table("step")
    with op.batch_alter_table("ingredient_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_line_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_ingredient_line_ingredient_id"))

    op.drop_table("ingredient_line")
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_cook_id"))

    op.drop_table("recipe")
    # ### end Alembic commands ###
