"""eaters and constraints

Revision ID: b0de70663ab7
Revises: 3ec1242366a9
Create Date: 2026-08-20 23:01:45.770637
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "b0de70663ab7"
down_revision: str | None = "3ec1242366a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eater",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "age_band",
            sa.Enum("INFANT", "CHILD", "ADULT", "ELDERLY", name="ageband"),
            nullable=False,
        ),
        sa.Column("appetite", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eater", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eater_cook_id"), ["cook_id"], unique=False)

    op.create_table(
        "eater_constraint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eater_id", sa.Integer(), nullable=False),
        sa.Column(
            "allergen",
            sa.Enum(
                "GLUTEN",
                "CRUSTACEANS",
                "EGGS",
                "FISH",
                "PEANUTS",
                "SOYBEANS",
                "MILK",
                "TREE_NUTS",
                "CELERY",
                "MUSTARD",
                "SESAME",
                "SULPHITES",
                "LUPIN",
                "MOLLUSCS",
                name="allergen",
            ),
            nullable=True,
        ),
        sa.Column("ingredient_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("MEDICAL", "ETHICAL", "INTOLERANCE", "PREFERENCE", name="severity"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["eater_id"],
            ["eater.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eater_constraint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eater_constraint_eater_id"), ["eater_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eater_constraint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eater_constraint_eater_id"))

    op.drop_table("eater_constraint")
    with op.batch_alter_table("eater", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eater_cook_id"))

    op.drop_table("eater")
    # ### end Alembic commands ###
