"""unit preferences

Revision ID: b4f60432b449
Revises: abfaaf38d543
Create Date: 2026-08-20 19:25:13.718397
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b4f60432b449"
down_revision: str | None = "abfaaf38d543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_preference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("LIQUID", "POWDER", "SOLID", "COUNTABLE", name="ingredientkind"),
            nullable=False,
        ),
        sa.Column(
            "unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cook_id", "kind", name="uq_unit_preference"),
    )
    with op.batch_alter_table("unit_preference", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unit_preference_cook_id"), ["cook_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unit_preference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unit_preference_cook_id"))

    op.drop_table("unit_preference")
    # ### end Alembic commands ###
