"""a recipe can be a version of another

A self-reference, and nullable: most recipes are not versions of anything, and a version
of a version is a perfectly ordinary thing for a cook to make.

Revision ID: bf9fe8c2c697
Revises: bae44bb72fac
Create Date: 2026-08-22 09:03:23.830503
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bf9fe8c2c697"
down_revision: str | None = "bae44bb72fac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("derived_from", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_recipe_derived_from"), ["derived_from"], unique=False)
        # Named, because SQLite rebuilds the table to add a constraint and batch mode
        # refuses to do that to something it cannot refer to afterwards.
        batch_op.create_foreign_key("fk_recipe_derived_from", "recipe", ["derived_from"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_constraint("fk_recipe_derived_from", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_recipe_derived_from"))
        batch_op.drop_column("derived_from")

    # ### end Alembic commands ###
