"""pantry stock and waste

Revision ID: ce4b4d2452d9
Revises: 07b3e4937b81
Create Date: 2026-08-21 12:01:45.954581
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "ce4b4d2452d9"
down_revision: str | None = "07b3e4937b81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("magnitude", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stock_item_cook_id"), ["cook_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stock_item_expires_on"), ["expires_on"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stock_item_ingredient_id"), ["ingredient_id"], unique=False
        )

    op.create_table(
        "waste",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cook_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("stock_item_id", sa.Integer(), nullable=True),
        sa.Column("magnitude", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "unit",
            sa.Enum(
                "MILLIGRAM",
                "GRAM",
                "KILOGRAM",
                "OUNCE",
                "POUND",
                "MILLILITRE",
                "CENTILITRE",
                "DECILITRE",
                "LITRE",
                "TEASPOON_METRIC",
                "TABLESPOON_METRIC",
                "CUP_METRIC",
                "TEASPOON_US",
                "TABLESPOON_US",
                "CUP_US",
                "FLUID_OUNCE_US",
                "FLUID_OUNCE_IMPERIAL",
                "PIECE",
                "SERVING",
                name="unit",
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Enum("SPOILED", "EXPIRED", "UNEATEN", "DAMAGED", "OTHER", name="wastereason"),
            nullable=False,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cook_id"],
            ["cook.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_item_id"],
            ["stock_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("waste", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_waste_cook_id"), ["cook_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_waste_ingredient_id"), ["ingredient_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_waste_stock_item_id"), ["stock_item_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("waste", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_waste_stock_item_id"))
        batch_op.drop_index(batch_op.f("ix_waste_ingredient_id"))
        batch_op.drop_index(batch_op.f("ix_waste_cook_id"))

    op.drop_table("waste")
    with op.batch_alter_table("stock_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_item_ingredient_id"))
        batch_op.drop_index(batch_op.f("ix_stock_item_expires_on"))
        batch_op.drop_index(batch_op.f("ix_stock_item_cook_id"))

    op.drop_table("stock_item")
    # ### end Alembic commands ###
