"""ingredient registry

Revision ID: fc7553d6568e
Revises: 05b83b30feab
Create Date: 2026-08-20 18:56:02.217386
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

revision: str = "fc7553d6568e"
down_revision: str | None = "05b83b30feab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("LIQUID", "POWDER", "SOLID", "COUNTABLE", name="ingredientkind"),
            nullable=False,
        ),
        sa.Column("density", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("origin", sa.Enum("SEED", "USER", name="origin"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingredient_slug"), ["slug"], unique=True)

    op.create_table(
        "ingredient_name",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("normalised", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("locale", "normalised", name="uq_ingredient_name"),
    )
    with op.batch_alter_table("ingredient_name", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingredient_name_ingredient_id"), ["ingredient_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ingredient_name_locale"), ["locale"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ingredient_name_normalised"), ["normalised"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_name", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_name_normalised"))
        batch_op.drop_index(batch_op.f("ix_ingredient_name_locale"))
        batch_op.drop_index(batch_op.f("ix_ingredient_name_ingredient_id"))

    op.drop_table("ingredient_name")
    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredient_slug"))

    op.drop_table("ingredient")
    # ### end Alembic commands ###
